name: Publish Docker image at DockerHub

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          LINEAR_SECRET: ${{ secrets.LINEAR_SECRET }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        run: npm test

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: trickerbackend/tricker_backend_image

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# name: Docker Build and ECR Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Run Test Workflow
#         uses: test.yml

#   build-and-deploy:
#     name: Build Docker Image and Deploy to ECR
#     runs-on: ubuntu-latest
#     needs: test
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.AWS_BACKEND_ROLE }}
#           aws-region: <"us-east-1">

#       - name: Build, tag, and push docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: my-ecr-repo #change to ECR repo
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


#     # TODO: Check if it is better to do it in this way
#       - name: Build Docker Image
#         run: docker build -t node:lts-alpine .

#       - name: Tag Docker Image
#         run: docker tag node:lts-alpine:latest ECR-Registry/tricker-backend:latest # Complete with ECR Registry or ask if I we to use IAM

#       - name: Push Docker Image to ECR
#         run: docker push ECR-Registry/tricker-backend:latest # Complete with ECR Registry or ask if I we to use IAM