name: Docker Build and ECR Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      # Insert steps here to run backend tests (reuse the existing test workflow)

  build-and-deploy:
    name: Build Docker Image and Deploy to ECR
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ECR-Registry # Complete with ECR Registry or ask if I we to use IAM
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Ask to make it a GH secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Ask to make it a GH secret
          aws-region: ECR-Region # Complete with ECR Region or ask if I we to use IAM

      - name: Build Docker Image
        run: docker build -t node:lts-alpine .

      - name: Tag Docker Image
        run: docker tag node:lts-alpine:latest ECR-Registry/tricker-backend:latest # Complete with ECR Registry or ask if I we to use IAM

      - name: Push Docker Image to ECR
        run: docker push ECR-Registry/tricker-backend:latest # Complete with ECR Registry or ask if I we to use IAM
